# Generated by Django 4.0.5 on 2022-07-06 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flashcards.apps.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', flashcards.apps.core.fields.OrderField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('deck_type', models.CharField(choices=[('word', 'Word'), ('normal', 'Normal'), ('phrasal', 'Phrasal Verbs'), ('expressions', 'Popular Expressions')], max_length=11, verbose_name='Deck type')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('zh', 'Simplified Chinese'), ('zh-tw', 'Traditional Chinese'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('iw', 'Hebrew'), ('hi', 'Hindi'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('la', 'Latin'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Portuguese Brazilian'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish')], max_length=5, verbose_name='Language')),
                ('cards', models.ManyToManyField(blank=True, through='deck.CardRelation', to='card.card')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.deck'),
        ),
    ]
