# Generated by Django 4.0.5 on 2022-07-07 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deck', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card'),
        ),
        migrations.AddField(
            model_name='cardrelation',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.deck'),
        ),
    ]
