# Generated by Django 4.0.5 on 2022-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_type',
            field=models.CharField(choices=[('word', 'Word'), ('normal', 'Normal'), ('phrasal', 'Phrasal Verbs'), ('expressions', 'Popular Expressions')], default='a', max_length=11, verbose_name='Deck type'),
            preserve_default=False,
        ),
    ]
