# Generated by Django 4.0.5 on 2022-07-05 19:19

from django.db import migrations, models
import django.db.models.deletion
import flashcards.apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_options_remove_card_order'),
        ('deck', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', flashcards.apps.core.fields.OrderField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.deck')),
            ],
        ),
    ]
