# Generated by Django 4.0.5 on 2022-07-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_deck_deck_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='description',
        ),
    ]
