# Generated by Django 4.0.5 on 2022-07-03 18:10

from django.db import migrations, models
import django.db.models.deletion
import flashcards.apps.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('language', models.CharField(max_length=5, verbose_name='Language')),
                ('order', flashcards.apps.core.fields.OrderField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('language', models.CharField(max_length=5, verbose_name='Language')),
                ('audio_phonetic', models.FileField(null=True, upload_to='phonetics/', verbose_name='Audio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordTranslated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_language', models.CharField(max_length=5, verbose_name='Language')),
                ('meanings', models.TextField(verbose_name='Meanings')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='card.word')),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=100, verbose_name='Headword')),
                ('definitions', models.TextField(verbose_name='Definitions')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='card.word')),
            ],
        ),
    ]
