# Generated by Django 4.0.5 on 2022-07-06 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('language', models.CharField(max_length=5, verbose_name='Language')),
                ('audio_phonetic', models.FileField(null=True, upload_to='phonetics/', verbose_name='Audio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=100, verbose_name='Headword')),
                ('for_language', models.CharField(choices=[('ar', 'Arabic'), ('zh', 'Simplified Chinese'), ('zh-tw', 'Traditional Chinese'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('iw', 'Hebrew'), ('hi', 'Hindi'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('la', 'Latin'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Portuguese Brazilian'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish')], max_length=5, verbose_name='Language')),
                ('meaning', models.TextField(verbose_name='Meaning')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='card.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=100, verbose_name='Headword')),
                ('for_language', models.CharField(choices=[('ar', 'Arabic'), ('zh', 'Simplified Chinese'), ('zh-tw', 'Traditional Chinese'), ('cs', 'Czech'), ('da', 'Danish'), ('nl', 'Dutch'), ('en', 'English'), ('fr', 'French'), ('de', 'German'), ('el', 'Greek'), ('iw', 'Hebrew'), ('hi', 'Hindi'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('la', 'Latin'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Portuguese Brazilian'), ('ru', 'Russian'), ('es', 'Spanish'), ('sv', 'Swedish'), ('th', 'Thai'), ('tr', 'Turkish')], max_length=5, verbose_name='Language')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='card.word')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('language', models.CharField(max_length=5, verbose_name='Language')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.word')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
