# Generated by Django 4.0.5 on 2022-07-08 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='for_language',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='for_language',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='headword_pos',
        ),
        migrations.RemoveField(
            model_name='worddefinition',
            name='headword_text',
        ),
        migrations.RemoveField(
            model_name='wordmeaning',
            name='meaning',
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='example',
            field=models.TextField(null=True, verbose_name='Example'),
        ),
        migrations.AddField(
            model_name='worddefinition',
            name='pos_tag',
            field=models.CharField(default='a', max_length=100, verbose_name='Pos Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordmeaning',
            name='meanings',
            field=models.TextField(default='a', verbose_name='Meanings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='audio_phonetic',
            field=models.URLField(null=True, verbose_name='Audio'),
        ),
        migrations.CreateModel(
            name='WordUserMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.wordmeaning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
