# Generated by Django 4.0.5 on 2022-07-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_word_for_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='language',
            field=models.CharField(max_length=7, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='wordmeaning',
            name='for_language',
            field=models.CharField(max_length=7, verbose_name='Language'),
        ),
    ]
