# Generated by Django 4.0.5 on 2022-07-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_options_remove_card_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meaning',
            new_name='WordDefinition',
        ),
        migrations.RenameModel(
            old_name='WordTranslated',
            new_name='WordMeaning',
        ),
    ]
