# Generated by Django 4.0.5 on 2022-07-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('card', '0003_remove_cardword_deck_remove_cardword_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('cardword', 'cardphrasalverb', 'cardexpressions')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='CardNormal',
        ),
    ]
