# Generated by Django 4.0.5 on 2022-07-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_wordusermeaning_meanings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordusermeaning',
            name='meaning',
        ),
        migrations.AddField(
            model_name='wordusermeaning',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.word'),
            preserve_default=False,
        ),
    ]
