# Generated by Django 4.0.5 on 2022-07-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_word_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio_phonetic',
            field=models.URLField(default='https://a.com.br', verbose_name='Audio'),
            preserve_default=False,
        ),
    ]
