# Generated by Django 4.0.5 on 2022-07-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_word_audio_phonetic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='language',
        ),
    ]
