# Generated by Django 4.0.5 on 2022-07-13 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('card', '0009_remove_card_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordUserDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_tag', models.CharField(choices=[('Adjective', 'Adjective'), ('Adverb', 'Adverb'), ('Conjunction', 'Conjunction'), ('Determiner', 'Determiner'), ('Modal', 'Modal'), ('Noun', 'Noun'), ('Preposition', 'Preposition'), ('Pronoun', 'Pronoun'), ('Verb', 'Verb'), ('Other', 'Other')], max_length=11, verbose_name='Pos Tag')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('example', models.TextField(null=True, verbose_name='Example')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.word')),
            ],
        ),
    ]
